# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c528cccd716a0fc8f63955ec19d4ec523de80b092812571a1529b6faa727e8a1a162a73c5048c8dca794ca7ca3302317edaf7f0d6520656f27e2c23595996cf5

test:
  secret_key_base: 9d71a23f612ae8489bad3ac16ff86b4358a3ae0c6b210bb762475de6e0705e0c86535140a69936af6942fc8317e2340739365c29e8a8040bfe9e5c117f6aeb81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
